ALTER TABLE public.page_settings
  ADD COLUMN IF NOT EXISTS fx_enabled boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS fx_density integer NOT NULL DEFAULT 140,
  ADD COLUMN IF NOT EXISTS fx_speed integer NOT NULL DEFAULT 40,
  ADD COLUMN IF NOT EXISTS fx_hue integer NOT NULL DEFAULT 225,
  ADD COLUMN IF NOT EXISTS fx_glow integer NOT NULL DEFAULT 60,
  ADD COLUMN IF NOT EXISTS fx_grid boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS fx_scan boolean NOT NULL DEFAULT true;